### ISSUE TITLE
Is there a way to save the outputted figures?

### ISSUE THREAD

**Issue by hxj5** [StatBiomed/SNPmanifold#1]
Thanks for the great tool, very user-friendly.

There are many figures outputted after running individual SNPmanifold functions in notebook. I was wondering is there a way, e.g., a parameter or function, to save those figures? It would be better if high-resolution figures can be exported.

**Comment by huangyh09** [comment]
@HoiManC, issue from xianjie. please click "watch" of the repository to receive notification.

**Comment by HoiManC** [comment]
@hxj5
Hi Xianjie, let's say you initialize SNPmanifold with `demo1 = SNPmanifold.SNP_VAE(...)`

You can use 
`demo1.filtering_summary(dpi = 300)`
`demo1.training_summary(dpi = 300)`
`demo1.clustering_summary(dpi = 300)`
`demo1.phylogeny_summary(dpi = 300)`
to regenerate figures with higher resolution.
